### ISSUE TITLE
не стоит публиковать конфигурации

### ISSUE THREAD

**Issue by ruskaof** [missmagenta/Lab_1#1]
https://github.com/missmagenta/Lab_1/blob/0e42ff9e8344da969ad6a9b9b0ef870cff0863fe/Lab_1.iml#L1-L11

**Comment by ruskaof** [comment]
также не стоит публиковать собранный .jar файл

**Comment by missmagenta** [comment]
Commit [f896b5b](https://github.com/missmagenta/Lab_1/commit/f896b5bdb0ffa5891af2aa9cbaa1e92f74521057)
